# Describe experimental structure.
# Keys: Experiment prefix. Replicates will be merged into a single overall experiment.
# Values: Biological replicate prefix to be merged. The workflow expects to find 
#         fastq/[prefix]_1.fq.gz and fastq[prefix]_2.fq.gz. We expect that all replicate prefixes
#         associated with their experiment prefix have a substring uniquely identifying them as a group.
#         If that is not true, an error will be generated. This helps avoid mis-merging replicates due to typos.
experiment_structure:
  EXP_KO:
    - KO_1
    - KO_2
    - KO_3
  EXP_Mock:
    - Mock_1
    - Mock_2
    - Mock_3

# Settings for email alerts
email_address: "skubi@ohsu.edu"
email_subject_error: "[Snakemake Alert] Failure"
email_body_error: "An error occurred in the EZH2 Knockout 1M-read test pipeline."
email_subject_success: "[Snakemake Alert] Success"
email_body_success: "The EZH2 Knockout 1M-read test pipeline has completed successfully."

# Reference genome information
# Assembly header is used by pairtools parse
# genomeID is used to get chromosome sizes by juicer_tools pre; a chromosome sizes file can be substituted.
# genome_prefix is the stem of the reference genome filename and indexes generated by bwa index.
# assembly_urls lists locations to download appropriate ***NO-ALTS*** reference genomes if they're not already in/linked in ./resources
assembly_header: "hg38"
genomeID: "hg38"
genome_prefix: "resources/hg38_noalts"
assembly_urls:
  hg38: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"

# From juicer tools pre documentation (https://github.com/aidenlab/juicer/wiki/Pre#restriction-site-file-format)
# IMPORTANT NOTE pre throws away reads that map to the same restriction fragment.
juicer_tools_pre_restriction_site_file: "resources/hg38_Arima.txt"

# location of chromsizes file, used by pairtools parse
chromsizes: "/home/groups/ravnica/projects/sciMET_GCC/230410_replication/ref/hg38.noalt.sizes"

# location of juicer_tools .jar
juicer_tools_jar: "/home/groups/ravnica/src/juicer/juicer_tools_1.22.01.jar"

# min mapq to filter in pairtools parse and juicer_tools pre
min_mapq: 10

# downsampling strategies. Valid options are numbers from 0-1 (uniform downsampling to that fraction of reads) and "min",
# which calculates the minimum total_mapped statistic from pairtools parse across all replicates, then downsamples each
# replicate by the fraction [min total_mapped]/[cur total_mapped]. Conceptually this is meant to downsample all replicates to
# roughly the same size.
downsample:
  - min

# resolutions/bin sizes to use in .hic/.mcool files
resolutions:
  - 1000
  - 2000
  - 5000
  - 10000
  - 25000
  - 50000
  - 100000
  - 250000
  - 500000
  - 1000000
  - 2500000
  - 5000000
  - 10000000

# Normalizations to compute with juicer_tools.
# Options: VC, VC_SQRT, KR,SCALE, GW_KR, GW_SCALE, GW_VC, INTER_KR, INTER_SCALE, INTER_VC
normalizations:
  - VC
  - VC_SQRT
  - KR
  - SCALE