experiment_structure:
  EXP1M_KO:
    - 1M_KO_1
    - 1M_KO_2
    - 1M_KO_3
  EXP1M_Mock:
    - 1M_Mock_1
    - 1M_Mock_2
    - 1M_Mock_3


assembly: "hg38"

assembly_urls:
  hg38: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"

chromsizes: "/home/groups/ravnica/projects/sciMET_GCC/230410_replication/ref/hg38.noalt.sizes"

juicer_tools_jar: "/home/groups/ravnica/src/juicer/juicer_tools_1.22.01.jar"

min_mapq: 10

downsample:
  - min

resolutions:
  - 1000
  - 2000
  - 5000
  - 10000
  - 20000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 5000000
